name: fluttersdk
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  atoa_sdk:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  intl: any
  regal: ^3.7.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
