// Mocks generated by Mockito 5.4.4 from annotations
// in atoa_sdk/test/src/controllers/bank_institutions_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:atoa_core/atoa_core.dart' as _i2;
import 'package:atoa_core/src/http_client/http_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaymentRequestData_0 extends _i1.SmartFake
    implements _i2.PaymentRequestData {
  _FakePaymentRequestData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentAuthResponse_1 extends _i1.SmartFake
    implements _i2.PaymentAuthResponse {
  _FakePaymentAuthResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionDetails_2 extends _i1.SmartFake
    implements _i2.TransactionDetails {
  _FakeTransactionDetails_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Atoa].
///
/// See the documentation for Mockito's code generation for more information.
class MockAtoa extends _i1.Mock implements _i2.Atoa {
  @override
  void initialize([
    _i3.AtoaDio? dio,
    Duration? connectionTimeout = const Duration(seconds: 20),
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            dio,
            connectionTimeout,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i2.BankInstitution>> fetchInstitutions(
          {String? searchTerm}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInstitutions,
          [],
          {#searchTerm: searchTerm},
        ),
        returnValue: _i4.Future<List<_i2.BankInstitution>>.value(
            <_i2.BankInstitution>[]),
        returnValueForMissingStub: _i4.Future<List<_i2.BankInstitution>>.value(
            <_i2.BankInstitution>[]),
      ) as _i4.Future<List<_i2.BankInstitution>>);

  @override
  _i4.Future<_i2.PaymentRequestData> getPaymentDetails(
    String? paymentRequestId, {
    _i2.CustomerDetails? customerDetails,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentDetails,
          [paymentRequestId],
          {#customerDetails: customerDetails},
        ),
        returnValue:
            _i4.Future<_i2.PaymentRequestData>.value(_FakePaymentRequestData_0(
          this,
          Invocation.method(
            #getPaymentDetails,
            [paymentRequestId],
            {#customerDetails: customerDetails},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PaymentRequestData>.value(_FakePaymentRequestData_0(
          this,
          Invocation.method(
            #getPaymentDetails,
            [paymentRequestId],
            {#customerDetails: customerDetails},
          ),
        )),
      ) as _i4.Future<_i2.PaymentRequestData>);

  @override
  _i4.Future<_i2.PaymentAuthResponse> getPaymentAuth(
          _i2.PaymentAuthRequestBody? payRequestBody) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentAuth,
          [payRequestBody],
        ),
        returnValue: _i4.Future<_i2.PaymentAuthResponse>.value(
            _FakePaymentAuthResponse_1(
          this,
          Invocation.method(
            #getPaymentAuth,
            [payRequestBody],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.PaymentAuthResponse>.value(
            _FakePaymentAuthResponse_1(
          this,
          Invocation.method(
            #getPaymentAuth,
            [payRequestBody],
          ),
        )),
      ) as _i4.Future<_i2.PaymentAuthResponse>);

  @override
  _i4.Future<_i2.TransactionDetails> getPaymentStatus(
          String? paymentIdempotencyId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentStatus,
          [paymentIdempotencyId],
        ),
        returnValue:
            _i4.Future<_i2.TransactionDetails>.value(_FakeTransactionDetails_2(
          this,
          Invocation.method(
            #getPaymentStatus,
            [paymentIdempotencyId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TransactionDetails>.value(_FakeTransactionDetails_2(
          this,
          Invocation.method(
            #getPaymentStatus,
            [paymentIdempotencyId],
          ),
        )),
      ) as _i4.Future<_i2.TransactionDetails>);
}
