include: package:very_good_analysis/analysis_options.5.1.0.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_expression_function_bodies: true
    no_default_cases: false
    lines_longer_than_80_chars: false