name: atoa_sdk
description: Atoa Flutter SDK
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  atoa_core:
    path: packages/atoa_core
  cached_network_image: ^3.3.1
  external_app_launcher: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_state_notifier: ^1.0.0
  freezed_annotation: ^2.4.1
  intl: any
  provider: ^6.1.1
  regal:
    git:
      url: git@github.com:ATOAPaymentsLimited/atoa-flutter-packages.git
      ref: v3.2.1
      path: packages/regal
  state_notifier: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
