name: atoa_flutter_sdk
description: Atoa Flutter SDK which can be used to initiate open source payment using `paymentRequestId` generated atoa backend.
version: 1.0.7
homepage: https://github.com/ATOAPaymentsLimited/flutter_atoa_sdk
repository: https://github.com/ATOAPaymentsLimited/flutter_atoa_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  atoa_core:
    path: packages/atoa_core
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  custom_sliding_segmented_control: ^1.8.1
  dotted_border: ^2.1.0
  expandable: ^5.0.1
  external_app_launcher: ^4.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_state_notifier: ^1.0.0
  flutter_svg: ^2.0.1
  flutter_widget_from_html_core: ^0.14.11
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  http: ^1.2.1
  injectable: ^2.3.2
  intl: ^0.19.0
  lottie: ^3.2.0
  nested: ^1.0.0
  provider: ^6.1.1
  regal:
    path: ../atoa-flutter-packages/packages/regal
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  state_notifier: ^1.0.0
  stream_transform: ^2.1.1
  url_launcher: ^6.2.3

dependency_overrides:
  vector_graphics: 1.1.15

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_gen:
  line_length: 80
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true # Enable package parameter
      class_name: Assets

flutter:
  generate: true
  uses-material-design:
    true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
