name: atoa_flutter_sdk
description: Atoa Flutter SDK which can be used to initiate open source payment using `paymentRequestId` generated atoa backend.
version: 1.0.6
homepage: https://github.com/ATOAPaymentsLimited/flutter_atoa_sdk
repository: https://github.com/ATOAPaymentsLimited/flutter_atoa_sdk
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  atoa_core:
    path: packages/atoa_core
  cached_network_image: ^3.3.1
  custom_sliding_segmented_control: ^1.8.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_state_notifier: ^1.0.0
  flutter_svg: ^2.0.9
  flutter_widget_from_html_core: ^0.14.11
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  intl: ^0.19.0
  nested: ^1.0.0
  provider: ^6.1.1
  regal: ^3.2.4
  shimmer: ^3.0.0
  state_notifier: ^1.0.0
  url_launcher: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
