name: atoa_core
description: Atoa Flutter SDK
version: 1.0.5
homepage: https://github.com/ATOAPaymentsLimited/flutter_atoa_sdk/tree/main/packages/atoa_core
repository: https://github.com/ATOAPaymentsLimited/flutter_atoa_sdk/tree/main/packages/atoa_core

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  very_good_analysis: ^5.1.0
dependencies:
  collection: ^1.18.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  shared_preferences: ^2.3.5
