name: fluttersdk
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+30

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  atoa_flutter_sdk:
    path: ../
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.1
  intl: ^0.19.0
  regal:
    path: ../../atoa-flutter-packages/packages/regal
  shared_preferences: ^2.2.2

dependency_overrides:
  vector_graphics: 1.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
