name: fluttersdk
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+30

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  atoa_flutter_sdk:
    path: ../
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.1
  intl: ^0.19.0
  regal: ^3.7.5
  shared_preferences: ^2.2.2

dependency_overrides:
  regal:
    git:
      url: https://github.com/ATOAPaymentsLimited/atoa-flutter-packages.git
      path: packages/regal
      ref: feat/light-mode-sdk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
