name: fluttersdk
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+45
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  atoa_flutter_sdk:
    path: ../
  connectivity_plus: ^4.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.1
  http: ^1.3.0
  intl: ^0.19.0
  provider: ^6.1.2
  regal: ^3.7.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
